title: EDA 1 - Estructuras de Datos y Algoritmos 1
description: Materiales de la asignatura Programación 2 / EDA 1 de UNLu
baseurl: ""
url: "https://unlu-prog-2.github.io"

plugins:
- jekyll-feed

markdown: GFM
